"""Synchronous API for pydoll.

This package exports the same names as ``pydoll``. The classes with an
asynchronous implementation (``Chrome``, ``Tab``, ``WebElement`` and the rest)
are facades generated by ``scripts/generate_sync_api.py`` in which every
``await``-able method blocks instead; see ``pydoll/sync/_runtime.py`` for how
the calls reach the event loop. Options, constants, events and extraction
models are the same objects as in the async API.

Example::

    from pydoll.sync import Chrome

    with Chrome() as browser:
        tab = browser.start()
        tab.go_to('https://example.com')
        print(tab.title())
"""

from pydoll import (
    ChromiumOptions,
    ExtractionModel,
    FetchEvent,
    Field,
    Key,
    NetworkEvent,
    PageEvent,
)
from pydoll.sync._generated import (
    Chrome,
    DownloadHandle,
    Edge,
    Keyboard,
    Mouse,
    Request,
    RequestHandle,
    Response,
    ResponseHandle,
    Scroll,
    ShadowRoot,
    Tab,
    WebElement,
)
from pydoll.sync._runtime import SyncError

__all__ = [
    'Chrome',
    'ChromiumOptions',
    'DownloadHandle',
    'Edge',
    'ExtractionModel',
    'FetchEvent',
    'Field',
    'Key',
    'Keyboard',
    'Mouse',
    'NetworkEvent',
    'PageEvent',
    'Request',
    'RequestHandle',
    'Response',
    'ResponseHandle',
    'Scroll',
    'ShadowRoot',
    'SyncError',
    'Tab',
    'WebElement',
]
