name: Release

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    name: "Version"
    outputs:
      version: ${{ steps.cz.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

      - name: Permissions
        run: |
          chown -R $(whoami) .

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Update Poetry version in pyproject.toml
        run: |
          poetry version "${{ steps.cz.outputs.version }}"
          git add pyproject.toml
          git commit -m "Update pyproject.toml to version ${{ steps.cz.outputs.version }}"
          git push origin HEAD

      - name: Update poetry.lock
        run: |
          poetry lock
          git add poetry.lock
          git commit -m "Update poetry.lock for version ${{ steps.cz.outputs.version }}"
          git push origin HEAD

  release:
    name: Release
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ needs.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
